### ISSUE TITLE
Lazarus Support Horse V2

### ISSUE THREAD

**Issue by CarlosHe** [HashLoad/horse#89]
Add support for Lazarus

**Comment by CarlosHe** [comment]
**CONVERT THE HORSE CORE AND OFFICIAL MIDDLEWARE**

**tasks**

- [ ] Convert Horse core
- [ ] Convert middleware horse/json
- [ ] Convert middleware horse/basic-auth
- [ ] Convert middleware horse/cors
- [ ] Convert middleware horse/stream
- [ ] Convert middleware horse/jwt
- [ ] Convert middleware horse/exception
- [ ] Convert middleware horse/logger
- [ ] Convert middleware horse/compression
