### ISSUE TITLE
Providers for Horse V2

### ISSUE THREAD

**Issue by CarlosHe** [HashLoad/horse#90]
Create providers for Horse

**Comment by CarlosHe** [comment]
**PROVIDERS FOR HORSE**

**tasks**

- [x] Create Delphi Console Application
- [x] Create Delphi ISAPP Application
- [x] Create Delphi CGI Application
- [x] Create Delphi Apache Application
- [x] Create Lazarus Console Application
- [x] Create Lazarus CGI Application
- [ ] Create Lazarus FastCGI Application
- [x] Create Lazarus Apache Application
