### ISSUE TITLE
Samples for Horse V2

### ISSUE THREAD

**Issue by CarlosHe** [HashLoad/horse#93]
Recreate and create the samples for Horse V2

**Comment by CarlosHe** [comment]
**SAMPLES FOR V2**

**tasks**

- [x] Delphi Console Application sample
- [ ] Delphi WinSrv sample
- [ ] Delphi Linux Daemon Application sample
- [ ] Delphi ISAPP Application sample
- [ ] Delphi CGI Application sample
- [ ] Delphi Apache Application sample
- [ ] Lazarus Console Application sample
- [ ] Lazarus CGI Application sample
- [ ] Lazarus FastCGI Application sample
- [ ] Lazarus Apache Application sample
